# URLs
TAIGA_SCHEME=https
TAIGA_DOMAIN=crm.appliway.com
SUBPATH=""
WEBSOCKETS_SCHEME=wss

# Secret
SECRET_KEY="taiga-secret-key-unique"

# PostgreSQL
POSTGRES_USER=taiga
POSTGRES_PASSWORD=taiga

# Email
EMAIL_BACKEND=smtp
EMAIL_HOST=smtp.hostinger.com
EMAIL_PORT=587
EMAIL_HOST_USER=teamproject@almightytechnology.pro
EMAIL_HOST_PASSWORD=c7#9Y~KJlXF
EMAIL_DEFAULT_FROM=teamproject@almightytechnology.pro
EMAIL_USE_TLS=True
EMAIL_USE_SSL=False

# RabbitMQ
RABBITMQ_USER=taiga
RABBITMQ_PASS=taiga
RABBITMQ_VHOST=taiga
RABBITMQ_ERLANG_COOKIE=secret-erlang-cookie

# Attachments
ATTACHMENTS_MAX_AGE=360
ENABLE_TELEMETRY=True
